# Generated by Django 2.2 on 2021-02-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to='products_img')),
                ('description', models.TextField(max_length=128, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='кол-во на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
        ),
    ]
