# Generated by Django 2.2 on 2021-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210207_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='gbuser',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
