# Generated by Django 2.2 on 2021-04-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210408_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='tags')),
                ('about_me', models.TextField(blank=True, verbose_name='about me')),
                ('gender', models.CharField(blank=True, choices=[('M', 'man'), ('W', 'woman')], max_length=1, verbose_name='gender')),
            ],
        ),
    ]
