# Generated by Django 2.2 on 2021-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='кол-во'),
        ),
    ]
